Soccer.Web/Controllers/GameController.cs
using FluentValidation;
using FluentValidation.AspNetCore;

using MediatR;

using Microsoft.AspNetCore.Mvc;

using Soccer.Web.Application.Commands.GameCommands;
using Soccer.Web.Application.Queries.GameQueries;
using Soccer.Web.Application.Queries.TeamQueries;
using Soccer.Web.Application.Responses;
using Soccer.Web.ViewModels;

namespace Soccer.Web.Controllers
{
    public class GameController : BaseController
    {
        private readonly IValidator<CreateGameCommand> createCommandValidator;
        private readonly IValidator<UpdateGameCommand> updateCommandValidator;

        public GameController(
            IMediator mediator,
            IValidator<CreateGameCommand> createCommandValidator,
            IValidator<UpdateGameCommand> updateCommandValidator) : base(mediator)
        {
            this.createCommandValidator = createCommandValidator ?? throw new ArgumentNullException(nameof(createCommandValidator));
            this.updateCommandValidator = updateCommandValidator ?? throw new ArgumentNullException(nameof(updateCommandValidator));
        }

        // GET: GameController
        public async Task<IActionResult> Index()
        {
            var viewModel = await mediator.Send(new GetAllGamesQuery());
            return View(viewModel.ToList());
        }

        // GET: GameController/Create
        public async Task<IActionResult> Create()
        {
            var teams = await mediator.Send(new GetAllTeamsQuery());

            var viewModel = new GameViewModel
            {
                AllTeams = teams.Select(t => new SelectTeamViewModel
                {
                    TeamId = t.Id,
                    TeamName = t.Name,
                    IsSelected = false
                }).ToList()
            };

            return View(viewModel);
        }

        // POST: GameController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(GameViewModel viewModel)
        {
            var utcDateTime = new DateTime(
                viewModel.Date.Year, 
                viewModel.Date.Month, 
                viewModel.Date.Day, 
                viewModel.Time.Hour, 
                viewModel.Time.Minute, 
                viewModel.Time.Second);
            utcDateTime = DateTime.SpecifyKind(utcDateTime, DateTimeKind.Utc);

            var command = new CreateGameCommand
            {
                DateAndTime = utcDateTime,
                Scores = viewModel.AllTeams.Where(team => team.IsSelected).Select(team => new GameTeam
                {
                    Score = team.Score,
                    TeamId = team.TeamId,
                }).ToList(),
                IsGameOver = viewModel.IsGameOver
            };

            var result = await createCommandValidator.ValidateAsync(command);
            if (!result.IsValid)
            {
                result.AddToModelState(ModelState, null);
                return View(viewModel);
            }

            try
            {
                await mediator.Send(command);

                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(viewModel);
            }
        }

        // GET: GameController/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            var query = new GetGameByIdQuery { Id = id };
            var model = await mediator.Send(query);

            if (model == null)
            {
                return NotFound();
            }

            var viewModel = new GameViewModel
            {
                Id = model.Id,
                Date = model.Date,
                Time = model.Time,
                IsGameOver = model.IsGameOver
            };
            
            var teams = await mediator.Send(new GetAllTeamsQuery());

            foreach (var team in teams)
            {
                var teamScore = model.GameTeams.SingleOrDefault(ts => ts.TeamId == team.Id);

                if (teamScore != null)
                {
                    var selectTeamViewModel = new SelectTeamViewModel
                    {
                        TeamId = team.Id,
                        TeamName = team.Name,
                        IsSelected = true,
                        Score = teamScore?.Score ?? 0
                    };

                    viewModel.AllTeams.Add(selectTeamViewModel);
                }
            }

            return View(viewModel);
        }

        // POST: GameController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(GameViewModel viewModel)
        {
            var command = new UpdateGameCommand
            {
                GameId = viewModel.Id,
                Scores = viewModel.AllTeams.Select(team => new GameTeam
                {
                    Score = team.Score,
                    TeamId = team.TeamId,
                }).ToList(),
                IsGameOver = viewModel.IsGameOver
            };

            var result = await updateCommandValidator.ValidateAsync(command);
            if (!result.IsValid)
            {
                result.AddToModelState(ModelState, null);
                return View(viewModel);
            }

            try
            {
                await mediator.Send(command);

                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(viewModel);
            }
        }
    }
}

Soccer.Web/Controllers/PlayerController.cs
using AutoMapper;

using FluentValidation;
using FluentValidation.AspNetCore;

using MediatR;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using Soccer.Web.Application.Commands.PlayerCommands;
using Soccer.Web.Application.Queries.PlayerQueries;
using Soccer.Web.Application.Queries.TeamQueries;
using Soccer.Web.ViewModels;


namespace Soccer.Web.Controllers
{
    public class PlayerController : BaseController
    {
        private readonly IMapper mapper;
        private readonly IValidator<CreatePlayerCommand> createCommandValidator;
        private readonly IValidator<UpdatePlayerCommand> updateCommandValidator;

        public PlayerController(
            IMediator mediator, 
            IMapper mapper,
            IValidator<CreatePlayerCommand> createCommandValidator,
            IValidator<UpdatePlayerCommand> updateCommandValidator) : base(mediator)
        {
            this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            this.createCommandValidator = createCommandValidator ?? throw new ArgumentNullException(nameof(createCommandValidator));
            this.updateCommandValidator = updateCommandValidator ?? throw new ArgumentNullException(nameof(updateCommandValidator));
        }

        // GET: PlayerController
        public async Task<IActionResult> Index(string searchString)
        {
            ViewData["CurrentFilter"] = searchString;

            IEnumerable<PlayerSummaryViewModel> viewModel = new List<PlayerSummaryViewModel>();

            if(!string.IsNullOrEmpty(searchString))
            {
                var playerViewModel = await mediator.Send(new SearchPlayerByCnpQuery() {CNP = searchString});

                if (playerViewModel != null)
                {
                    viewModel = new List<PlayerSummaryViewModel> {playerViewModel};
                }
            }
            else
            {
                viewModel = await mediator.Send(new GetAllPlayersQuery());
            }
            
            return View(viewModel);
        }

 
        // GET: PlayerController/Create
        public async Task<IActionResult> Create()
        {
            await LoadTeams();

            return View();
        }

        // POST: PlayerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PlayerViewModel viewModel)
        {
            var command = mapper.Map<CreatePlayerCommand>(viewModel);

            var result = await createCommandValidator.ValidateAsync(command);

            if (!result.IsValid)
            {
                result.AddToModelState(ModelState, null);
                await LoadTeams();
                return View();
            }

            try
            {
                await mediator.Send(command);

                return RedirectToAction(nameof(Index));
            }
            catch(ValidationException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                await LoadTeams();
                return View();
            }
        }

        // GET: PlayerController/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            var query = new GetPlayerByIdQuery { Id = id };
            var viewModel = await mediator.Send(query);

            if (viewModel == null)
            {
                return NotFound();
            }

            await LoadTeams();

            return View(viewModel);
        }

        // POST: PlayerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PlayerViewModel viewModel)
        {
            var command = mapper.Map<UpdatePlayerCommand>(viewModel);

            var result = await updateCommandValidator.ValidateAsync(command);

            if (!result.IsValid)
            {
                result.AddToModelState(ModelState, null);
                await LoadTeams();
                return View();
            }

            try
            {
                await mediator.Send(command);

                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                await LoadTeams();
                return View();
            }
        }

        private async Task LoadTeams()
        {
            var teams = await mediator.Send(new GetAllTeamsQuery());
            ViewBag.Teams = teams.Select(team => new SelectListItem { Value = team.Id.ToString(), Text = team.Name });
        }
    }
}

Soccer.Web/Views/Shared/_FormLayout.cshtml
@{
    Layout = "_Layout";
}

@RenderBody()

@section Scripts {
    <!-- Bootstrap DatePicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css" type="text/css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js" type="text/javascript"></script>
    <!-- Bootstrap DatePicker -->

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        /// <summary>
        /// Client side validation.
        /// Adds the 'is-valid' attribute to the input control if it passes validation
        /// Adds the 'is-invalid' attribute to the input control if it does not pass validation
        /// </summary>
        $(function () {
            var valSettings = $("form").data("validator").settings;
            valSettings.highlight = wrap($.validator.defaults.highlight, highlightDecorator);
            valSettings.unhighlight = wrap($.validator.defaults.unhighlight, unhighlightDecorator);
        });

        function wrap(functionToWrap, beforeFunction) {
            return function () {
                var args = Array.prototype.slice.call(arguments);
                beforeFunction.apply(this, args);
                return functionToWrap.apply(this, args);
            };
        };

        function highlightDecorator(element, errorClass, validClass) {
            $(element).addClass("is-invalid").removeClass(validClass);
        }
        function unhighlightDecorator(element, errorClass, validClass) {
            $(element).addClass(validClass).removeClass("is-invalid");
        }
    </script>
    
    @await RenderSectionAsync("FormScripts", required: false)
}

Soccer.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Soccer.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Soccer.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Soccer Game</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="nav navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="Index">Players</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Games</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Soccer.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>